charList={
	'!':{
		'char_exc_1':{
			'premultiply':2879,
			'imgName':'thumb',
			'baseline':238,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1022, 2646], [1032, 2601]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':168,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_exc_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':83,
		},
	},
	"'":{
		'char_osg_1':{
			'premultiply':923,
			'imgName':'thumb',
			'baseline':593,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2008, 2035]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':-77,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':173,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_osg_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':110,
		},
	},
	'.':{
		'char_per_1':{
			'premultiply':518,
			'imgName':'thumb',
			'baseline':247,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1853, 2465]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':236,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_per_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':26,
		},
	},
	'2':{
		'char_two_1':{
			'premultiply':3203,
			'imgName':'thumb',
			'baseline':205,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[4755, 1446]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':238,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_two_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':17,
		},
	},
	'5':{
		'char_five_1':{
			'premultiply':3437,
			'imgName':'thumb',
			'baseline':214,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[4889, 1549]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':202,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_five_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':17,
		},
	},
	'8':{
		'char_eight_1':{
			'premultiply':3398,
			'imgName':'thumb',
			'baseline':242,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[3539, 1857]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':210,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_eight_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':42,
		},
	},
	'9':{
		'char_nine_1':{
			'premultiply':3867,
			'imgName':'thumb',
			'baseline':214,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[4341, 1824]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':220,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_nine_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':42,
		},
	},
	'A':{
		'char_A_cap_1':{
			'premultiply':3085,
			'imgName':'thumb',
			'baseline':216,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[873, 343]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[855, 291, 68, 79],
			'alphaReach':2,
			'spacingRight':220,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_A_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':48,
		},
		'char_A_cap_2':{
			'premultiply':2929,
			'imgName':'thumb',
			'baseline':207,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet_2.png',
			'charSamplePoints':[[1167, 319]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1143, 275, 70, 75],
			'alphaReach':2,
			'spacingRight':220,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_A_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':10,
		},
	},
	'a':{
		'char_a_low_2':{
			'premultiply':2030,
			'imgName':'thumb',
			'baseline':159,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1521, 318], [1517, 309]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1479, 298, 57, 46],
			'alphaReach':2,
			'spacingRight':201,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_a_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':17,
		},
		'char_a_low_1':{
			'premultiply':2030,
			'imgName':'thumb',
			'baseline':159,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1328, 316]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1289, 299, 61, 53],
			'alphaReach':2,
			'spacingRight':198,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_a_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':14,
		},
	},
	'B':{
		'char_B_cap_1':{
			'premultiply':2773,
			'imgName':'thumb',
			'baseline':198,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1944, 273]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1928, 239, 51, 71],
			'alphaReach':2,
			'spacingRight':221,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_B_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':53,
		},
	},
	'b':{
		'char_b_low_1':{
			'premultiply':2773,
			'imgName':'thumb',
			'baseline':224,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2551, 244]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2536, 212, 48, 71],
			'alphaReach':2,
			'spacingRight':202,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_b_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':56,
		},
	},
	'C':{
		'char_C_cap_2':{
			'premultiply':2600,
			'imgName':'thumb',
			'baseline':213,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1012, 457]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[989, 395, 73, 69],
			'alphaReach':2,
			'spacingRight':234,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_C_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':16,
		},
		'char_C_cap_3':{
			'premultiply':2539,
			'imgName':'thumb',
			'baseline':218,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1117, 451]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1092, 393, 64, 65],
			'alphaReach':2,
			'spacingRight':242,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_C_cap_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':17,
		},
		'char_C_cap_1':{
			'premultiply':3048,
			'imgName':'thumb',
			'baseline':206,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[823, 453]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[808, 400, 59, 61],
			'alphaReach':2,
			'spacingRight':235,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_C_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':24,
		},
	},
	'c':{
		'char_c_low_1':{
			'premultiply':1992,
			'imgName':'thumb',
			'baseline':201,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1352, 437]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1330, 403, 51, 40],
			'alphaReach':2,
			'spacingRight':231,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_c_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_c_low_2':{
			'premultiply':2376,
			'imgName':'thumb',
			'baseline':189,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1426, 402]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1385, 394, 69, 45],
			'alphaReach':2,
			'spacingRight':230,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_c_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
	},
	'D':{
		'char_D_cap_1':{
			'premultiply':3543,
			'imgName':'thumb',
			'baseline':187,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1614, 397], [1632, 359]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1602, 353, 62, 76],
			'alphaReach':2,
			'spacingRight':221,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_D_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':39,
		},
		'char_D_cap_2':{
			'premultiply':3359,
			'imgName':'thumb',
			'baseline':178,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1816, 397], [1813, 374]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1788, 345, 72, 68],
			'alphaReach':2,
			'spacingRight':240,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_D_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':60,
		},
	},
	'd':{
		'char_d_low_2':{
			'premultiply':3064,
			'imgName':'thumb',
			'baseline':235,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2053, 372], [2028, 372]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2013, 330, 59, 68],
			'alphaReach':2,
			'spacingRight':237,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_d_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':23,
		},
		'char_d_low_1':{
			'premultiply':2953,
			'imgName':'thumb',
			'baseline':235,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1991, 376]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1947, 333, 65, 64],
			'alphaReach':2,
			'spacingRight':255,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_d_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
	},
	'E':{
		'char_E_cap_1':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':207,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2514, 341], [2522, 312], [2513, 317]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2501, 307, 57, 55],
			'alphaReach':2,
			'spacingRight':251,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_E_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':4,
		},
	},
	'e':{
		'char_e_low_2':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':212,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1030, 498]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1017, 477, 57, 51],
			'alphaReach':2,
			'spacingRight':240,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_e_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':18,
		},
		'char_e_low_1':{
			'premultiply':2070,
			'imgName':'thumb',
			'baseline':223,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[935, 501]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[922, 482, 53, 51],
			'alphaReach':2,
			'spacingRight':253,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_e_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':7,
		},
	},
	'F':{
		'char_F_cap_1':{
			'premultiply':2863,
			'imgName':'thumb',
			'baseline':205,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1260, 492]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1225, 459, 71, 67],
			'alphaReach':2,
			'spacingRight':205,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_F_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':9,
		},
	},
	'f':{
		'char_f_low_1':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':178,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1524, 481]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1497, 460, 57, 54],
			'alphaReach':2,
			'spacingRight':256,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_f_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
		'char_f_low_3':{
			'premultiply':2734,
			'imgName':'thumb',
			'baseline':187,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1827, 469]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1797, 446, 70, 56],
			'alphaReach':2,
			'spacingRight':256,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_f_low_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':8,
		},
		'char_f_low_2':{
			'premultiply':2382,
			'imgName':'thumb',
			'baseline':187,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1427, 490]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1398, 461, 61, 58],
			'alphaReach':2,
			'spacingRight':255,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_f_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':7,
		},
	},
	'G':{
		'char_G_cap_2':{
			'premultiply':3710,
			'imgName':'thumb',
			'baseline':198,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2078, 503], [2119, 476], [2128, 479]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2046, 435, 95, 74],
			'alphaReach':2,
			'spacingRight':251,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_G_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_G_cap_1':{
			'premultiply':4765,
			'imgName':'thumb',
			'baseline':179,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2238, 474]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2156, 434, 122, 67],
			'alphaReach':2,
			'spacingRight':247,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_G_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
	},
	'g':{
		'char_g_low_1':{
			'premultiply':4632,
			'imgName':'thumb',
			'baseline':92,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2582, 459]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2535, 443, 61, 82],
			'alphaReach':2,
			'spacingRight':221,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_g_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':60,
		},
		'char_g_low_2':{
			'premultiply':4612,
			'imgName':'thumb',
			'baseline':99,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2621, 464]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2599, 437, 77, 94],
			'alphaReach':2,
			'spacingRight':230,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_g_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':69,
		},
	},
	'H':{
		'char_H_cap_1':{
			'premultiply':3984,
			'imgName':'thumb',
			'baseline':180,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1565, 579], [1609, 567], [1591, 598]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1528, 546, 102, 64],
			'alphaReach':2,
			'spacingRight':238,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_H_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
		'char_H_cap_2':{
			'premultiply':3671,
			'imgName':'thumb',
			'baseline':183,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1815, 582], [1844, 581]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1771, 545, 94, 73],
			'alphaReach':2,
			'spacingRight':239,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_H_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'h':{
		'char_h_low_2':{
			'premultiply':2460,
			'imgName':'thumb',
			'baseline':233,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2186, 600], [2156, 592]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2149, 542, 49, 63],
			'alphaReach':2,
			'spacingRight':223,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_h_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':50,
		},
		'char_h_low_1':{
			'premultiply':2617,
			'imgName':'thumb',
			'baseline':231,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1913, 585]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1893, 544, 59, 67],
			'alphaReach':2,
			'spacingRight':236,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_h_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':36,
		},
	},
	'I':{
		'char_I_cap_1':{
			'premultiply':2890,
			'imgName':'thumb',
			'baseline':196,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1031, 700]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1007, 655, 74, 54],
			'alphaReach':2,
			'spacingRight':221,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_I_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_I_cap_2':{
			'premultiply':3828,
			'imgName':'thumb',
			'baseline':185,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[730, 717]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[705, 656, 98, 70],
			'alphaReach':2,
			'spacingRight':185,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_I_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
	},
	'i':{
		'char_i_low_2':{
			'premultiply':2656,
			'imgName':'thumb',
			'baseline':239,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1263, 696], [1275, 649]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1255, 641, 28, 68],
			'alphaReach':2,
			'spacingRight':152,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_i_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':80,
		},
		'char_i_low_1':{
			'premultiply':2851,
			'imgName':'thumb',
			'baseline':237,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1136, 685], [1149, 641]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1126, 634, 32, 73],
			'alphaReach':2,
			'spacingRight':144,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_i_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':72,
		},
	},
	'J':{
		'char_J_cap_2':{
			'premultiply':3046,
			'imgName':'thumb',
			'baseline':185,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1718, 682]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1672, 654, 78, 72],
			'alphaReach':2,
			'spacingRight':188,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_J_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':38,
		},
		'char_J_cap_1':{
			'premultiply':2668,
			'imgName':'thumb',
			'baseline':199,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1451, 659]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1410, 641, 74, 76],
			'alphaReach':2,
			'spacingRight':206,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_J_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':38,
		},
	},
	'K':{
		'char_K_cap_1':{
			'premultiply':3554,
			'imgName':'thumb',
			'baseline':209,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2199, 696]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':207,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_K_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'k':{
		'char_k_low_1':{
			'premultiply':2890,
			'imgName':'thumb',
			'baseline':213,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[951, 803]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':226,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_k_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'l':{
		'char_l_low_2':{
			'premultiply':2808,
			'imgName':'thumb',
			'baseline':232,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1902, 833]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1895, 787, 22, 53],
			'alphaReach':2,
			'spacingRight':165,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_l_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':88,
		},
		'char_l_low_1':{
			'premultiply':2843,
			'imgName':'thumb',
			'baseline':226,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1784, 819], [1778, 831]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1772, 786, 22, 54],
			'alphaReach':2,
			'spacingRight':158,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_l_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':91,
		},
	},
	'M':{
		'char_M_cap_1':{
			'premultiply':3600,
			'imgName':'thumb',
			'baseline':195,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2437, 786]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2370, 773, 77, 68],
			'alphaReach':2,
			'spacingRight':252,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_M_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_M_cap_2':{
			'premultiply':4171,
			'imgName':'thumb',
			'baseline':181,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2194, 778]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2105, 769, 98, 75],
			'alphaReach':2,
			'spacingRight':255,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_M_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':11,
		},
		'char_M_cap_3':{
			'premultiply':3506,
			'imgName':'thumb',
			'baseline':198,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[919, 864]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[840, 848, 92, 77],
			'alphaReach':2,
			'spacingRight':255,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_M_cap_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
	},
	'm':{
		'char_m_low_2':{
			'premultiply':3259,
			'imgName':'thumb',
			'baseline':182,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1176, 891]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1112, 869, 74, 47],
			'alphaReach':2,
			'spacingRight':252,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_m_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_m_low_1':{
			'premultiply':2705,
			'imgName':'thumb',
			'baseline':182,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[993, 894]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[982, 874, 68, 42],
			'alphaReach':2,
			'spacingRight':252,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_m_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
	},
	'N':{
		'char_N_cap_2':{
			'premultiply':3209,
			'imgName':'thumb',
			'baseline':207,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1870, 890]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1844, 870, 80, 72],
			'alphaReach':2,
			'spacingRight':226,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_N_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_N_cap_1':{
			'premultiply':3593,
			'imgName':'thumb',
			'baseline':197,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1669, 923]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1611, 854, 92, 81],
			'alphaReach':2,
			'spacingRight':232,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_N_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
	},
	'n':{
		'char_n_low_1':{
			'premultiply':2497,
			'imgName':'thumb',
			'baseline':209,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2042, 924]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2037, 896, 45, 42],
			'alphaReach':2,
			'spacingRight':226,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_n_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_n_low_2':{
			'premultiply':2323,
			'imgName':'thumb',
			'baseline':209,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1952, 928]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1946, 896, 46, 48],
			'alphaReach':2,
			'spacingRight':228,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_n_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':12,
		},
	},
	'O':{
		'char_O_cap_2':{
			'premultiply':2890,
			'imgName':'thumb',
			'baseline':204,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[873, 967]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[811, 947, 74, 63],
			'alphaReach':2,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
		'char_O_cap_3':{
			'premultiply':2734,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[995, 946]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[936, 937, 70, 65],
			'alphaReach':1,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
		'char_O_cap_1':{
			'premultiply':2695,
			'imgName':'thumb',
			'baseline':216,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2434, 889]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2376, 876, 69, 65],
			'alphaReach':2,
			'spacingRight':250,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_O_cap_4':{
			'premultiply':2812,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[770, 963]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[707, 946, 72, 70],
			'alphaReach':1,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_4.png',
			'degRotation':0,
			'contrast':0,
			'spacingLeft':15,
		},
		'char_O_cap_5':{
			'premultiply':2812,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[875, 963]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[812, 948, 72, 61],
			'alphaReach':2,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_5.png',
			'degRotation':0,
			'contrast':80,
			'spacingLeft':15,
		},
	},
	'o':{
		'char_o_low_1':{
			'premultiply':2031,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1137, 973]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1105, 964, 52, 49],
			'alphaReach':2,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_o_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'P':{
		'char_P_cap_1':{
			'premultiply':3125,
			'imgName':'thumb',
			'baseline':231,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1780, 990]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':197,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_P_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'p':{
		'char_p_low_1':{
			'premultiply':3085,
			'imgName':'thumb',
			'baseline':138,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2273, 1037]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':224,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_p_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':62,
		},
	},
	'R':{
		'char_R_cap_1':{
			'premultiply':4531,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2259, 1140]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':204,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_R_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':43,
		},
	},
	'r':{
		'char_r_low_1':{
			'premultiply':1992,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1446, 1189]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':240,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_r_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':19,
		},
	},
	'S':{
		'char_S_cap_1':{
			'premultiply':3046,
			'imgName':'thumb',
			'baseline':222,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2126, 1215]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':220,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_S_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':49,
		},
	},
	's':{
		'char_s_low_1':{
			'premultiply':2104,
			'imgName':'thumb',
			'baseline':202,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2415, 1261]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':215,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_s_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':56,
		},
	},
	'T':{
		'char_T_cap_1':{
			'premultiply':3988,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[866, 1271]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':146,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_T_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':47,
		},
	},
	't':{
		'char_t_low_1':{
			'premultiply':2656,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1566, 1312]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':182,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_t_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':39,
		},
	},
	'U':{
		'char_U_cap_1':{
			'premultiply':3476,
			'imgName':'thumb',
			'baseline':230,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2506, 1354]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':246,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_U_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'u':{
		'char_u_low_1':{
			'premultiply':2382,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1872, 1426]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_u_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'V':{
		'char_V_cap_1':{
			'premultiply':3164,
			'imgName':'thumb',
			'baseline':214,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2475, 1476]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_V_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'v':{
		'char_v_low_1':{
			'premultiply':1992,
			'imgName':'thumb',
			'baseline':230,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1176, 1492]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':244,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_v_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'W':{
		'char_W_cap_1':{
			'premultiply':4648,
			'imgName':'thumb',
			'baseline':199,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1645, 1514]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':199,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_W_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'w':{
		'char_w_low_1':{
			'premultiply':4218,
			'imgName':'thumb',
			'baseline':171,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2471, 1631]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':252,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_w_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':7,
		},
	},
	'X':{
		'char_X_cap_1':{
			'premultiply':3554,
			'imgName':'thumb',
			'baseline':213,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[894, 1682]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':236,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_X_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':26,
		},
	},
	'x':{
		'char_x_low_1':{
			'premultiply':2304,
			'imgName':'thumb',
			'baseline':213,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1911, 1713]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':236,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_x_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':26,
		},
	},
	'y':{
		'char_y_low_1':{
			'premultiply':3437,
			'imgName':'thumb',
			'baseline':123,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[874, 1929]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':236,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_y_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':26,
		},
	},
}
