charList={
	'A':{
		'char_A_cap_1':{
			'premultiply':3085,
			'imgName':'thumb',
			'baseline':216,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[873, 343]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[855, 291, 68, 79],
			'alphaReach':2,
			'spacingRight':111,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_A_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':19,
		},
		'char_A_cap_2':{
			'premultiply':2929,
			'imgName':'thumb',
			'baseline':218,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet_2.png',
			'charSamplePoints':[[1167, 319]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1143, 275, 70, 75],
			'alphaReach':2,
			'spacingRight':115,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_A_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':10,
		},
	},
	'a':{
		'char_a_low_2':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':159,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1521, 318], [1517, 309]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1479, 298, 57, 46],
			'alphaReach':2,
			'spacingRight':73,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_a_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':3,
		},
		'char_a_low_1':{
			'premultiply':2382,
			'imgName':'thumb',
			'baseline':159,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1328, 316]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1289, 299, 61, 53],
			'alphaReach':2,
			'spacingRight':76,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_a_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':2,
		},
	},
	'B':{
		'char_B_cap_1':{
			'premultiply':2773,
			'imgName':'thumb',
			'baseline':159,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1944, 273]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1928, 239, 51, 71],
			'alphaReach':2,
			'spacingRight':93,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_B_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':53,
		},
	},
	'b':{
		'char_b_low_1':{
			'premultiply':2773,
			'imgName':'thumb',
			'baseline':159,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2551, 244]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2536, 212, 48, 71],
			'alphaReach':2,
			'spacingRight':87,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_b_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':45,
		},
	},
	'C':{
		'char_C_cap_2':{
			'premultiply':2600,
			'imgName':'thumb',
			'baseline':226,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1012, 457]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[989, 395, 73, 69],
			'alphaReach':2,
			'spacingRight':128,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_C_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':3,
		},
		'char_C_cap_3':{
			'premultiply':2539,
			'imgName':'thumb',
			'baseline':227,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1117, 451]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1092, 393, 64, 65],
			'alphaReach':2,
			'spacingRight':128,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_C_cap_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_C_cap_1':{
			'premultiply':3048,
			'imgName':'thumb',
			'baseline':226,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[823, 453]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[808, 400, 59, 61],
			'alphaReach':2,
			'spacingRight':125,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_C_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':12,
		},
	},
	'c':{
		'char_c_low_1':{
			'premultiply':1992,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1352, 437]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1330, 403, 51, 40],
			'alphaReach':2,
			'spacingRight':128,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_c_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
		'char_c_low_2':{
			'premultiply':2376,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1426, 402]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1385, 394, 69, 45],
			'alphaReach':2,
			'spacingRight':128,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_c_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':1,
		},
	},
	'D':{
		'char_D_cap_1':{
			'premultiply':2968,
			'imgName':'thumb',
			'baseline':187,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1614, 397], [1632, 359]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1602, 353, 62, 76],
			'alphaReach':2,
			'spacingRight':104,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_D_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':39,
		},
		'char_D_cap_2':{
			'premultiply':2812,
			'imgName':'thumb',
			'baseline':169,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1816, 397], [1813, 374]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1788, 345, 72, 68],
			'alphaReach':2,
			'spacingRight':127,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_D_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':60,
		},
	},
	'd':{
		'char_d_low_2':{
			'premultiply':2656,
			'imgName':'thumb',
			'baseline':235,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2053, 372], [2028, 372]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2013, 330, 59, 68],
			'alphaReach':2,
			'spacingRight':109,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_d_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':23,
		},
		'char_d_low_1':{
			'premultiply':2539,
			'imgName':'thumb',
			'baseline':235,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1991, 376]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1947, 333, 65, 64],
			'alphaReach':2,
			'spacingRight':127,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_d_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
	},
	'E':{
		'char_E_cap_1':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':215,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2514, 341], [2522, 312], [2513, 317]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2501, 307, 57, 55],
			'alphaReach':2,
			'spacingRight':123,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_E_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':4,
		},
	},
	'e':{
		'char_e_low_2':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':220,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1030, 498]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1017, 477, 57, 51],
			'alphaReach':2,
			'spacingRight':64,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_e_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':64,
		},
		'char_e_low_1':{
			'premultiply':2070,
			'imgName':'thumb',
			'baseline':223,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[935, 501]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[922, 482, 53, 51],
			'alphaReach':2,
			'spacingRight':125,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_e_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':7,
		},
	},
	'F':{
		'char_F_cap_1':{
			'premultiply':2863,
			'imgName':'thumb',
			'baseline':220,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1260, 492]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1225, 459, 71, 67],
			'alphaReach':2,
			'spacingRight':93,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_F_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':9,
		},
	},
	'f':{
		'char_f_low_1':{
			'premultiply':2226,
			'imgName':'thumb',
			'baseline':178,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1524, 481]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1497, 460, 57, 54],
			'alphaReach':2,
			'spacingRight':128,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_f_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
		'char_f_low_3':{
			'premultiply':2734,
			'imgName':'thumb',
			'baseline':187,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1827, 469]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1797, 446, 70, 56],
			'alphaReach':2,
			'spacingRight':128,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_f_low_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':8,
		},
		'char_f_low_2':{
			'premultiply':2382,
			'imgName':'thumb',
			'baseline':187,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1427, 490]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1398, 461, 61, 58],
			'alphaReach':2,
			'spacingRight':127,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_f_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':7,
		},
	},
	'G':{
		'char_G_cap_2':{
			'premultiply':3710,
			'imgName':'thumb',
			'baseline':198,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2078, 503], [2119, 476], [2128, 479]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2046, 435, 95, 74],
			'alphaReach':2,
			'spacingRight':123,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_G_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_G_cap_1':{
			'premultiply':4765,
			'imgName':'thumb',
			'baseline':179,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2238, 474]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2156, 434, 122, 67],
			'alphaReach':2,
			'spacingRight':119,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_G_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':5,
		},
	},
	'g':{
		'char_g_low_1':{
			'premultiply':3233,
			'imgName':'thumb',
			'baseline':92,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2582, 459]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2535, 443, 61, 82],
			'alphaReach':2,
			'spacingRight':93,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_g_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':60,
		},
		'char_g_low_2':{
			'premultiply':3671,
			'imgName':'thumb',
			'baseline':99,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2621, 464]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2599, 437, 77, 94],
			'alphaReach':2,
			'spacingRight':102,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_g_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':69,
		},
	},
	'H':{
		'char_H_cap_1':{
			'premultiply':3984,
			'imgName':'thumb',
			'baseline':188,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1565, 579], [1609, 567], [1591, 598]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1528, 546, 102, 64],
			'alphaReach':2,
			'spacingRight':110,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_H_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
		'char_H_cap_2':{
			'premultiply':3671,
			'imgName':'thumb',
			'baseline':194,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1815, 582], [1844, 581]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1771, 545, 94, 73],
			'alphaReach':2,
			'spacingRight':111,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_H_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
	},
	'h':{
		'char_h_low_2':{
			'premultiply':2460,
			'imgName':'thumb',
			'baseline':233,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2186, 600], [2156, 592]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2149, 542, 49, 63],
			'alphaReach':2,
			'spacingRight':95,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_h_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':50,
		},
		'char_h_low_1':{
			'premultiply':2617,
			'imgName':'thumb',
			'baseline':231,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1913, 585]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1893, 544, 59, 67],
			'alphaReach':2,
			'spacingRight':108,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_h_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':36,
		},
	},
	'I':{
		'char_I_cap_1':{
			'premultiply':2890,
			'imgName':'thumb',
			'baseline':196,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1031, 700]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1007, 655, 74, 54],
			'alphaReach':2,
			'spacingRight':93,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_I_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_I_cap_2':{
			'premultiply':3828,
			'imgName':'thumb',
			'baseline':199,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[730, 717]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[705, 656, 98, 70],
			'alphaReach':2,
			'spacingRight':57,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_I_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
	},
	'i':{
		'char_i_low_2':{
			'premultiply':2656,
			'imgName':'thumb',
			'baseline':239,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1263, 696], [1275, 649]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1255, 641, 28, 68],
			'alphaReach':2,
			'spacingRight':24,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_i_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':80,
		},
		'char_i_low_1':{
			'premultiply':2851,
			'imgName':'thumb',
			'baseline':237,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1136, 685], [1149, 641]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1126, 634, 32, 73],
			'alphaReach':2,
			'spacingRight':13,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_i_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':72,
		},
	},
	'J':{
		'char_J_cap_2':{
			'premultiply':3046,
			'imgName':'thumb',
			'baseline':200,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1718, 682]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1672, 654, 78, 72],
			'alphaReach':2,
			'spacingRight':60,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_J_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':38,
		},
		'char_J_cap_1':{
			'premultiply':2668,
			'imgName':'thumb',
			'baseline':205,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1451, 659]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1410, 641, 74, 76],
			'alphaReach':2,
			'spacingRight':78,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_J_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':38,
		},
	},
	'l':{
		'char_l_low_2':{
			'premultiply':2808,
			'imgName':'thumb',
			'baseline':232,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1902, 833]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1895, 787, 22, 53],
			'alphaReach':2,
			'spacingRight':37,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_l_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':88,
		},
		'char_l_low_1':{
			'premultiply':2843,
			'imgName':'thumb',
			'baseline':226,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1784, 819], [1778, 831]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1772, 786, 22, 54],
			'alphaReach':2,
			'spacingRight':30,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_l_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':91,
		},
	},
	'M':{
		'char_M_cap_1':{
			'premultiply':3007,
			'imgName':'thumb',
			'baseline':212,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2437, 786]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2370, 773, 77, 68],
			'alphaReach':2,
			'spacingRight':124,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_M_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_M_cap_2':{
			'premultiply':3259,
			'imgName':'thumb',
			'baseline':190,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2194, 778]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2105, 769, 98, 75],
			'alphaReach':2,
			'spacingRight':127,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_M_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':11,
		},
		'char_M_cap_3':{
			'premultiply':3259,
			'imgName':'thumb',
			'baseline':198,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[919, 864]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[840, 848, 92, 77],
			'alphaReach':2,
			'spacingRight':127,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_M_cap_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
	},
	'm':{
		'char_m_low_2':{
			'premultiply':3051,
			'imgName':'thumb',
			'baseline':182,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1176, 891]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1112, 869, 74, 47],
			'alphaReach':2,
			'spacingRight':124,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_m_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_m_low_1':{
			'premultiply':2705,
			'imgName':'thumb',
			'baseline':182,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[993, 894]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[982, 874, 68, 42],
			'alphaReach':2,
			'spacingRight':124,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_m_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
	},
	'N':{
		'char_N_cap_2':{
			'premultiply':3209,
			'imgName':'thumb',
			'baseline':218,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1870, 890]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1844, 870, 80, 72],
			'alphaReach':2,
			'spacingRight':98,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_N_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_N_cap_1':{
			'premultiply':3593,
			'imgName':'thumb',
			'baseline':207,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1669, 923]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1611, 854, 92, 81],
			'alphaReach':2,
			'spacingRight':104,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_N_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
	},
	'n':{
		'char_n_low_1':{
			'premultiply':2497,
			'imgName':'thumb',
			'baseline':209,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2042, 924]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2037, 896, 45, 42],
			'alphaReach':2,
			'spacingRight':98,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_n_low_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':6,
		},
		'char_n_low_2':{
			'premultiply':2323,
			'imgName':'thumb',
			'baseline':209,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[1952, 928]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[1946, 896, 46, 48],
			'alphaReach':2,
			'spacingRight':100,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_n_low_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':12,
		},
	},
	'O':{
		'char_O_cap_2':{
			'premultiply':2890,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[873, 967]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[811, 947, 74, 63],
			'alphaReach':2,
			'spacingRight':116,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_2.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
		'char_O_cap_3':{
			'premultiply':2734,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[995, 946]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[936, 937, 70, 65],
			'alphaReach':1,
			'spacingRight':116,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_3.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':15,
		},
		'char_O_cap_1':{
			'premultiply':2695,
			'imgName':'thumb',
			'baseline':228,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[2434, 889]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[2376, 876, 69, 65],
			'alphaReach':2,
			'spacingRight':122,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_1.png',
			'degRotation':0,
			'contrast':65,
			'spacingLeft':13,
		},
		'char_O_cap_4':{
			'premultiply':2812,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[770, 963]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[707, 946, 72, 70],
			'alphaReach':1,
			'spacingRight':116,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_4.png',
			'degRotation':0,
			'contrast':0,
			'spacingLeft':15,
		},
		'char_O_cap_5':{
			'premultiply':2812,
			'imgName':'thumb',
			'baseline':210,
			'textBaseFile':'E:/projects/pxlTextGenerator/tempAlphabet.png',
			'charSamplePoints':[[875, 963]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[812, 948, 72, 61],
			'alphaReach':2,
			'spacingRight':116,
			'fileName':'E:/projects/pxlTextGenerator/textCharacterOutput/char_O_cap_5.png',
			'degRotation':0,
			'contrast':80,
			'spacingLeft':15,
		},
	},
}
