pageList=[
	{
		"pageFlip":0,
		"spaceSize":50,
		"lineData":[
			{
				"wordData":[
					{
						"chars":[
							{
								"premultiply":0.417975,
								"key":"char_L_cap_1",
								"res":[107,107],
								"char":"L",
								"resMax":[107,107],
								"offset":[-25,-17],
								"spacingRight":71,
								"spacingLeft":25,
								"data":None,
								"baseline":92
							},
							{
								"premultiply":0.340275,
								"key":"char_e_low_4",
								"res":[87,87],
								"char":"e",
								"resMax":[87,87],
								"offset":[41,10],
								"spacingRight":71,
								"spacingLeft":5,
								"data":None,
								"baseline":65
							},
							{
								"premultiply":0.3405,
								"key":"char_t_low_3",
								"res":[87,87],
								"char":"t",
								"resMax":[87,87],
								"offset":[96,-7],
								"spacingRight":57,
								"spacingLeft":16,
								"data":None,
								"baseline":82
							},
							{
								"premultiply":0.31005,
								"key":"char_s_low_2",
								"res":[79,79],
								"char":"s",
								"resMax":[79,79],
								"offset":[121,13],
								"spacingRight":66,
								"spacingLeft":32,
								"data":None,
								"baseline":62
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.3405,
								"key":"char_t_low_4",
								"res":[87,87],
								"char":"t",
								"resMax":[87,87],
								"offset":[222,-7],
								"spacingRight":58,
								"spacingLeft":15,
								"data":None,
								"baseline":82
							},
							{
								"premultiply":0.2325,
								"key":"char_r_low_3",
								"res":[59,59],
								"char":"r",
								"resMax":[59,59],
								"offset":[271,19],
								"spacingRight":52,
								"spacingLeft":9,
								"data":None,
								"baseline":56
							},
							{
								"premultiply":0.5259,
								"key":"char_y_low_4",
								"res":[134,134],
								"char":"y",
								"resMax":[134,134],
								"offset":[276,23],
								"spacingRight":116,
								"spacingLeft":47,
								"data":None,
								"baseline":52
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.345975,
								"key":"char_t_low_1",
								"res":[88,88],
								"char":"t",
								"resMax":[88,88],
								"offset":[422,-9],
								"spacingRight":69,
								"spacingLeft":20,
								"data":None,
								"baseline":84
							},
							{
								"premultiply":0.362625,
								"key":"char_h_low_3",
								"res":[92,92],
								"char":"h",
								"resMax":[92,92],
								"offset":[474,-10],
								"spacingRight":76,
								"spacingLeft":17,
								"data":None,
								"baseline":85
							},
							{
								"premultiply":0.307275,
								"key":"char_i_low_2",
								"res":[78,78],
								"char":"i",
								"resMax":[78,78],
								"offset":[520,-1],
								"spacingRight":45,
								"spacingLeft":30,
								"data":None,
								"baseline":76
							},
							{
								"premultiply":0.31005,
								"key":"char_s_low_2",
								"res":[79,79],
								"char":"s",
								"resMax":[79,79],
								"offset":[533,13],
								"spacingRight":66,
								"spacingLeft":32,
								"data":None,
								"baseline":62
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.33495,
								"key":"char_a_low_1",
								"res":[85,85],
								"char":"a",
								"resMax":[85,85],
								"offset":[643,13],
								"spacingRight":68,
								"spacingLeft":6,
								"data":None,
								"baseline":62
							},
							{
								"premultiply":0.501,
								"key":"char_g_low_2",
								"res":[128,128],
								"char":"g",
								"resMax":[128,128],
								"offset":[664,27],
								"spacingRight":100,
								"spacingLeft":47,
								"data":None,
								"baseline":48
							},
							{
								"premultiply":0.296175,
								"key":"char_a_low_3",
								"res":[75,75],
								"char":"a",
								"resMax":[75,75],
								"offset":[761,14],
								"spacingRight":59,
								"spacingLeft":3,
								"data":None,
								"baseline":61
							},
							{
								"premultiply":0.31005,
								"key":"char_i_low_4",
								"res":[79,79],
								"char":"i",
								"resMax":[79,79],
								"offset":[792,-1],
								"spacingRight":39,
								"spacingLeft":28,
								"data":None,
								"baseline":76
							},
							{
								"premultiply":0.246375,
								"key":"char_n_low_3",
								"res":[63,63],
								"char":"n",
								"resMax":[63,63],
								"offset":[827,23],
								"spacingRight":58,
								"spacingLeft":4,
								"data":None,
								"baseline":52
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					}
				],
				"fontScale":1.0,
				"spaceWidth":50,
				"lineOffsets":[885,0]
			},
			{
				"wordData":[
					{
						"chars":[
							{
								"premultiply":0.4152,
								"key":"char_S_cap_4",
								"res":[106,106],
								"char":"S",
								"resMax":[106,106],
								"offset":[-30,57],
								"spacingRight":80,
								"spacingLeft":30,
								"data":None,
								"baseline":93
							},
							{
								"premultiply":0.39855,
								"key":"char_h_low_2",
								"res":[102,102],
								"char":"h",
								"resMax":[102,102],
								"offset":[28,63],
								"spacingRight":81,
								"spacingLeft":22,
								"data":None,
								"baseline":87
							},
							{
								"premultiply":0.33495,
								"key":"char_a_low_1",
								"res":[85,85],
								"char":"a",
								"resMax":[85,85],
								"offset":[103,88],
								"spacingRight":68,
								"spacingLeft":6,
								"data":None,
								"baseline":62
							},
							{
								"premultiply":0.351525,
								"key":"char_l_low_5",
								"res":[89,89],
								"char":"l",
								"resMax":[89,89],
								"offset":[138,66],
								"spacingRight":54,
								"spacingLeft":33,
								"data":None,
								"baseline":84
							},
							{
								"premultiply":0.337725,
								"key":"char_l_low_2",
								"res":[86,86],
								"char":"l",
								"resMax":[86,86],
								"offset":[160,68],
								"spacingRight":50,
								"spacingLeft":32,
								"data":None,
								"baseline":82
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.487125,
								"key":"char_w_low_2",
								"res":[124,124],
								"char":"w",
								"resMax":[124,124],
								"offset":[259,64],
								"spacingRight":119,
								"spacingLeft":1,
								"data":None,
								"baseline":86
							},
							{
								"premultiply":0.307275,
								"key":"char_e_low_2",
								"res":[78,78],
								"char":"e",
								"resMax":[78,78],
								"offset":[376,89],
								"spacingRight":63,
								"spacingLeft":2,
								"data":None,
								"baseline":61
							},
							{
								"premultiply":0.345975,
								"key":"char_exc_2",
								"res":[88,88],
								"char":"!",
								"resMax":[88,88],
								"offset":[405,65],
								"spacingRight":50,
								"spacingLeft":34,
								"data":None,
								"baseline":85
							},
							{
								"premultiply":0.3654,
								"key":"char_qus_1",
								"res":[93,93],
								"char":"?",
								"resMax":[93,93],
								"offset":[426,62],
								"spacingRight":66,
								"spacingLeft":29,
								"data":None,
								"baseline":88
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					}
				],
				"fontScale":1.0,
				"spaceWidth":50,
				"lineOffsets":[492,75]
			}
		],
		"fontScale":0.75,
		"pageIndentBottom":1948,
		"pageIndentLeft":150,
		"pageIndentRight":1500,
		"pageIndentTop":100,
		"inputText":"""Lets try this again
Shall we!?""",
		"lineHeight":75,
		"charSeed":0.0,
		"lineIndent":50
	},
	{
		"pageFlip":0,
		"spaceSize":63,
		"lineData":[
			{
				"wordData":[
					{
						"chars":[
							{
								"premultiply":0.276354,
								"key":"char_M_cap_4",
								"res":[70,70],
								"char":"M",
								"resMax":[70,70],
								"offset":[-7,22],
								"spacingRight":62,
								"spacingLeft":7,
								"data":None,
								"baseline":53
							},
							{
								"premultiply":0.174174,
								"key":"char_a_low_1",
								"res":[44,44],
								"char":"a",
								"resMax":[44,44],
								"offset":[52,43],
								"spacingRight":35,
								"spacingLeft":3,
								"data":None,
								"baseline":32
							},
							{
								"premultiply":0.273468,
								"key":"char_y_low_4",
								"res":[70,70],
								"char":"y",
								"resMax":[70,70],
								"offset":[63,48],
								"spacingRight":60,
								"spacingLeft":24,
								"data":None,
								"baseline":27
							},
							{
								"premultiply":0.208689,
								"key":"char_b_low_1",
								"res":[53,53],
								"char":"b",
								"resMax":[53,53],
								"offset":[100,28],
								"spacingRight":40,
								"spacingLeft":23,
								"data":None,
								"baseline":47
							},
							{
								"premultiply":0.118053,
								"key":"char_e_low_1",
								"res":[30,30],
								"char":"e",
								"resMax":[30,30],
								"offset":[140,49],
								"spacingRight":28,
								"spacingLeft":0,
								"data":None,
								"baseline":26
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.17823,
								"key":"char_a_low_2",
								"res":[45,45],
								"char":"a",
								"resMax":[45,45],
								"offset":[229,42],
								"spacingRight":36,
								"spacingLeft":2,
								"data":None,
								"baseline":33
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.190008,
								"key":"char_m_low_3",
								"res":[48,48],
								"char":"m",
								"resMax":[48,48],
								"offset":[326,40],
								"spacingRight":48,
								"spacingLeft":2,
								"data":None,
								"baseline":35
							},
							{
								"premultiply":0.161226,
								"key":"char_u_low_1",
								"res":[41,41],
								"char":"u",
								"resMax":[41,41],
								"offset":[374,44],
								"spacingRight":40,
								"spacingLeft":0,
								"data":None,
								"baseline":31
							},
							{
								"premultiply":0.179907,
								"key":"char_l_low_1",
								"res":[46,46],
								"char":"l",
								"resMax":[46,46],
								"offset":[397,32],
								"spacingRight":28,
								"spacingLeft":17,
								"data":None,
								"baseline":43
							},
							{
								"premultiply":0.191451,
								"key":"char_t_low_2",
								"res":[49,49],
								"char":"t",
								"resMax":[49,49],
								"offset":[414,30],
								"spacingRight":38,
								"spacingLeft":11,
								"data":None,
								"baseline":45
							},
							{
								"premultiply":0.159783,
								"key":"char_i_low_2",
								"res":[40,40],
								"char":"i",
								"resMax":[40,40],
								"offset":[437,36],
								"spacingRight":23,
								"spacingLeft":15,
								"data":None,
								"baseline":39
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.205803,
								"key":"char_p_low_1",
								"res":[52,52],
								"char":"p",
								"resMax":[52,52],
								"offset":[508,51],
								"spacingRight":47,
								"spacingLeft":15,
								"data":None,
								"baseline":24
							},
							{
								"premultiply":0.154011,
								"key":"char_a_low_3",
								"res":[39,39],
								"char":"a",
								"resMax":[39,39],
								"offset":[553,44],
								"spacingRight":31,
								"spacingLeft":2,
								"data":None,
								"baseline":31
							},
							{
								"premultiply":0.26052,
								"key":"char_g_low_2",
								"res":[66,66],
								"char":"g",
								"resMax":[66,66],
								"offset":[560,50],
								"spacingRight":52,
								"spacingLeft":24,
								"data":None,
								"baseline":25
							},
							{
								"premultiply":0.159783,
								"key":"char_e_low_2",
								"res":[40,40],
								"char":"e",
								"resMax":[40,40],
								"offset":[611,43],
								"spacingRight":33,
								"spacingLeft":1,
								"data":None,
								"baseline":32
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					}
				],
				"fontScale":1.0,
				"spaceWidth":63,
				"lineOffsets":[644,0]
			},
			{
				"wordData":[
					{
						"chars":[
							{
								"premultiply":0.383877,
								"key":"char_W_cap_4",
								"res":[98,98],
								"char":"W",
								"resMax":[98,98],
								"offset":[-11,111],
								"spacingRight":88,
								"spacingLeft":11,
								"data":None,
								"baseline":69
							},
							{
								"premultiply":0.161226,
								"key":"char_i_low_4",
								"res":[41,41],
								"char":"i",
								"resMax":[41,41],
								"offset":[63,141],
								"spacingRight":20,
								"spacingLeft":14,
								"data":None,
								"baseline":39
							},
							{
								"premultiply":0.184236,
								"key":"char_l_low_4",
								"res":[47,47],
								"char":"l",
								"resMax":[47,47],
								"offset":[66,136],
								"spacingRight":28,
								"spacingLeft":17,
								"data":None,
								"baseline":44
							},
							{
								"premultiply":0.184236,
								"key":"char_l_low_4",
								"res":[47,47],
								"char":"l",
								"resMax":[47,47],
								"offset":[77,136],
								"spacingRight":28,
								"spacingLeft":17,
								"data":None,
								"baseline":44
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.191451,
								"key":"char_t_low_2",
								"res":[49,49],
								"char":"t",
								"resMax":[49,49],
								"offset":[157,135],
								"spacingRight":38,
								"spacingLeft":11,
								"data":None,
								"baseline":45
							},
							{
								"premultiply":0.207246,
								"key":"char_h_low_2",
								"res":[53,53],
								"char":"h",
								"resMax":[53,53],
								"offset":[184,135],
								"spacingRight":42,
								"spacingLeft":11,
								"data":None,
								"baseline":45
							},
							{
								"premultiply":0.151125,
								"key":"char_i_low_3",
								"res":[38,38],
								"char":"i",
								"resMax":[38,38],
								"offset":[212,142],
								"spacingRight":22,
								"spacingLeft":14,
								"data":None,
								"baseline":38
							},
							{
								"premultiply":0.148278,
								"key":"char_s_low_1",
								"res":[37,37],
								"char":"s",
								"resMax":[37,37],
								"offset":[222,150],
								"spacingRight":32,
								"spacingLeft":12,
								"data":None,
								"baseline":30
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.253305,
								"key":"char_w_low_2",
								"res":[64,64],
								"char":"w",
								"resMax":[64,64],
								"offset":[316,136],
								"spacingRight":62,
								"spacingLeft":1,
								"data":None,
								"baseline":44
							},
							{
								"premultiply":0.103662,
								"key":"char_o_low_4",
								"res":[26,26],
								"char":"o",
								"resMax":[26,26],
								"offset":[378,155],
								"spacingRight":26,
								"spacingLeft":0,
								"data":None,
								"baseline":25
							},
							{
								"premultiply":0.112281,
								"key":"char_r_low_1",
								"res":[28,28],
								"char":"r",
								"resMax":[28,28],
								"offset":[402,153],
								"spacingRight":26,
								"spacingLeft":2,
								"data":None,
								"baseline":27
							},
							{
								"premultiply":0.215904,
								"key":"char_k_low_3",
								"res":[55,55],
								"char":"k",
								"resMax":[55,55],
								"offset":[409,132],
								"spacingRight":38,
								"spacingLeft":19,
								"data":None,
								"baseline":48
							},
							{
								"premultiply":0.190008,
								"key":"char_qus_1",
								"res":[48,48],
								"char":"?",
								"resMax":[48,48],
								"offset":[432,135],
								"spacingRight":34,
								"spacingLeft":15,
								"data":None,
								"baseline":45
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					}
				],
				"fontScale":1.0,
				"spaceWidth":63,
				"lineOffsets":[466,105]
			},
			{
				"wordData":[
					{
						"chars":[
							{
								"premultiply":0.261963,
								"key":"char_I_cap_2",
								"res":[67,67],
								"char":"I",
								"resMax":[67,67],
								"offset":[-16,230],
								"spacingRight":52,
								"spacingLeft":16,
								"data":None,
								"baseline":55
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					},
					{
						"chars":[
							{
								"premultiply":0.210132,
								"key":"char_d_low_2",
								"res":[53,53],
								"char":"d",
								"resMax":[53,53],
								"offset":[85,238],
								"spacingRight":36,
								"spacingLeft":14,
								"data":None,
								"baseline":47
							},
							{
								"premultiply":0.162669,
								"key":"char_u_low_2",
								"res":[41,41],
								"char":"u",
								"resMax":[41,41],
								"offset":[121,254],
								"spacingRight":41,
								"spacingLeft":0,
								"data":None,
								"baseline":31
							},
							{
								"premultiply":0.148278,
								"key":"char_n_low_1",
								"res":[37,37],
								"char":"n",
								"resMax":[37,37],
								"offset":[160,255],
								"spacingRight":35,
								"spacingLeft":2,
								"data":None,
								"baseline":30
							},
							{
								"premultiply":0.1209,
								"key":"char_n_low_4",
								"res":[30,30],
								"char":"n",
								"resMax":[30,30],
								"offset":[193,259],
								"spacingRight":30,
								"spacingLeft":2,
								"data":None,
								"baseline":26
							},
							{
								"premultiply":0.105495,
								"key":"char_o_low_2",
								"res":[27,27],
								"char":"o",
								"resMax":[27,27],
								"offset":[223,260],
								"spacingRight":26,
								"spacingLeft":0,
								"data":None,
								"baseline":25
							}
						],
						"fontScale":1.0,
						"size":[0,0]
					}
				],
				"fontScale":1.0,
				"spaceWidth":63,
				"lineOffsets":[249,210]
			}
		],
		"fontScale":0.39,
		"pageIndentBottom":1948,
		"pageIndentLeft":150,
		"pageIndentRight":1500,
		"pageIndentTop":100,
		"inputText":"""Maybe a multi page
Will this work?
I dunno""",
		"lineHeight":105,
		"charSeed":0.0,
		"lineIndent":50
	}
]
