charList={
	'a':{
		'char_a_low_2':{
			'premultiply':2731,
			'imgName':'thumb',
			'baseline':230,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages	extBase_AaBb.png',
			'charSamplePoints':[[930, 336]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':242,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/pxl_textCharacterOutput/char_a_low_2.png',
			'degRotation':195,
			'contrast':100,
			'spacingLeft':5,
		},
		'char_a_low_1':{
			'premultiply':2916,
			'imgName':'thumb',
			'baseline':224,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages	extBase_AaBb.png',
			'charSamplePoints':[[728, 331]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':243,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/pxl_textCharacterOutput/char_a_low_1.png',
			'degRotation':215,
			'contrast':85,
			'spacingLeft':8,
		},
	},
	'A':{
		'char_A_cap_1':{
			'premultiply':4392,
			'imgName':'thumb',
			'baseline':249,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages	extBase_AaBb.png',
			'charSamplePoints':[[1284, 113]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':238,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/pxl_textCharacterOutput/char_A_cap_1.png',
			'degRotation':0,
			'contrast':0,
			'spacingLeft':23,
		},
		'char_A_cap_2':{
			'premultiply':4798,
			'imgName':'thumb',
			'baseline':236,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages	extBase_AaBb.png',
			'charSamplePoints':[[2263, 185]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':238,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/pxl_textCharacterOutput/char_A_cap_2.png',
			'degRotation':154,
			'contrast':0,
			'spacingLeft':23,
		},
		'char_A_cap_3':{
			'premultiply':4761,
			'imgName':'thumb',
			'baseline':236,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages	extBase_AaBb.png',
			'charSamplePoints':[[2257, 191], [2319, 30]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':238,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/pxl_textCharacterOutput/char_A_cap_3.png',
			'degRotation':174,
			'contrast':0,
			'spacingLeft':23,
		},
	},
}
