charList={
	'1':{
		'char_one_2':{
			'premultiply':6953,
			'imgName':'thumb',
			'baseline':242,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages\textBase_123.png',
			'charSamplePoints':[[1178, 99]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':187,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/textCharacterOutput/char_one_2.png',
			'degRotation':-1733,
			'contrast':100,
			'spacingLeft':71,
		},
		'char_one_3':{
			'premultiply':6953,
			'imgName':'thumb',
			'baseline':242,
			'textBaseFile':'E:\projects\pxlTextGenerator\dieceAlphabet\pxl_textBases_origImages\textBase_123.png',
			'charSamplePoints':[[1816, 182]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':187,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/textCharacterOutput/char_one_3.png',
			'degRotation':-1733,
			'contrast':100,
			'spacingLeft':71,
		},
		'char_one_1':{
			'premultiply':6953,
			'imgName':'thumb',
			'baseline':242,
			'textBaseFile':'E:/projects/pxlTextGenerator/dieceAlphabet\pxl_textBases_origImages/textBase_123.png',
			'charSamplePoints':[[1613, 135]],
			'paddingTop':0,
			'imgPath':'localthumb',
			'imgFolder':'local',
			'paddingBottom':0,
			'rect':[0, 0, 256, 256],
			'alphaReach':2,
			'spacingRight':187,
			'fileName':'E:/projects/pxlTextGenerator/dieceAlphabet/textCharacterOutput/char_one_1.png',
			'degRotation':-1399,
			'contrast':100,
			'spacingLeft':71,
		},
	},
}
